In [3]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Libraries Loaded")

Libraries Loaded

In [2]:
import pandas as pd
import numpy as np

In [4]:
customers = pd.read_csv("../Data/Raw/customers.csv")

products = pd.read_csv("../Data/Raw/products.csv")

inventory = pd.read_csv("../Data/Raw/inventory.csv")

suppliers = pd.read_csv("../Data/Raw/suppliers.csv")

sales = pd.read_csv("../Data/Raw/sales_transactions.csv")

print("Loaded")

Loaded

In [5]:
datasets = {
"customers":customers,
"products":products,
"inventory":inventory,
"suppliers":suppliers,
"sales":sales
}

In [6]:
customers.shape

(25400, 6)

In [7]:
customers.head()

,customer_id,customer_name,customer_type,hospital_type,city,registration_date
0,CUS000001,Global 0,Pharmacy,NaN,Hyderabad,2024-08-29
1,CUS000002,Metro 1,Pharmacy,NaN,Pune,2019-03-18
2,CUS000003,Global 2,Pharmacy,NaN,Ahmedabad,2022-09-09
3,CUS000004,Apex 3,Hospital,Government,Mumbai,2021-10-07
4,CUS000005,Apex 4,Pharmacy,NaN,Mumbai,2021-12-02

In [8]:
customers.columns

Index(['customer_id', 'customer_name', 'customer_type', 'hospital_type',
       'city', 'registration_date'],
      dtype='object')

In [9]:
customers.isnull().sum()

customer_id              0
customer_name            0
customer_type            0
hospital_type        19719
city                     0
registration_date        0
dtype: int64

In [10]:
customers["customer_type"].value_counts()

customer_type
Pharmacy       15275
Hospital        6327
Distributor     3798
Name: count, dtype: int64

In [11]:
customers.groupby(
"customer_type"
)["hospital_type"].apply(
lambda x:x.isnull().sum()
)

customer_type
Distributor     3798
Hospital         646
Pharmacy       15275
Name: hospital_type, dtype: int64

In [12]:
customers.loc[
customers["customer_type"]!="Hospital",
"hospital_type"
]="Not Applicable"

In [13]:
customers["hospital_type"]=customers[
"hospital_type"
].fillna(
"Unknown Hospital"
)

In [14]:
customers.isnull().sum()

customer_id          0
customer_name        0
customer_type        0
hospital_type        0
city                 0
registration_date    0
dtype: int64

In [15]:
customers.duplicated().sum()

np.int64(400)

In [16]:
customers.drop_duplicates(inplace=True)

In [17]:
customers.shape

(25000, 6)

In [18]:
customers.duplicated().sum()

np.int64(0)

In [19]:
customers.dtypes

customer_id          object
customer_name        object
customer_type        object
hospital_type        object
city                 object
registration_date    object
dtype: object

In [20]:
customers["registration_date"] = pd.to_datetime(
    customers["registration_date"],
    errors="coerce"
)

In [21]:
customers.dtypes

customer_id                  object
customer_name                object
customer_type                object
hospital_type                object
city                         object
registration_date    datetime64[ns]
dtype: object

In [22]:
customers["registration_date"].isnull().sum()

np.int64(0)

In [23]:
customers["registration_date"].describe()

count                         25000
mean     2021-12-28 13:46:40.512000
min             2018-01-01 00:00:00
25%             2020-01-08 00:00:00
50%             2021-12-26 12:00:00
75%             2023-12-21 00:00:00
max             2025-12-30 00:00:00
Name: registration_date, dtype: object

In [24]:
customers["city"].unique()

array(['Hyderabad', 'Pune', 'Ahmedabad', 'Mumbai', 'Delhi', 'Hosp',
       'MUMBAI', 'mumbai'], dtype=object)

In [25]:
customers["city"] = (
    customers["city"]
    .str.strip()
    .str.title()
)

In [26]:
customers["city"].unique()

array(['Hyderabad', 'Pune', 'Ahmedabad', 'Mumbai', 'Delhi', 'Hosp'],
      dtype=object)

In [27]:
customers["city"].value_counts()

city
Mumbai       7181
Delhi        5527
Pune         4508
Hyderabad    4306
Ahmedabad    2965
Hosp          513
Name: count, dtype: int64

In [28]:
customers["city"] = customers["city"].replace(
    "Hosp",
    "Unknown"
)

In [29]:
customers["city"].value_counts()

city
Mumbai       7181
Delhi        5527
Pune         4508
Hyderabad    4306
Ahmedabad    2965
Unknown       513
Name: count, dtype: int64

In [31]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        25000 non-null  object
 1   customer_name      25000 non-null  object
 2   customer_type      25000 non-null  object
 3   hospital_type      25000 non-null  object
 4   city               25000 non-null  object
 5   registration_date  25000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.3+ MB

In [32]:
customers.shape

(25000, 6)

In [33]:
customers.duplicated().sum()

np.int64(0)

In [35]:
import os

os.makedirs(
"../Data/Cleaned",
exist_ok=True
)

In [36]:
customers.to_csv(
"../Data/Cleaned/customers_clean.csv",
index=False
)

In [37]:
print("customers.csv saved")

customers.csv saved

In [38]:
products.isnull().sum()

product_id       0
medicine_name    0
category         0
manufacturer     0
cost_price       0
selling_price    0
expiry_days      0
dtype: int64

In [39]:
products.duplicated().sum()

np.int64(0)

In [40]:
products.dtypes

product_id        object
medicine_name     object
category          object
manufacturer      object
cost_price       float64
selling_price    float64
expiry_days        int64
dtype: object

In [41]:
products["category"].unique()

array(['Antibiotics', 'Respiratory', 'Analgesics', 'Gastro', 'Diabetes',
       'Neurology', 'Dermatology', 'Cardiology'], dtype=object)

In [42]:
products["medicine_name"].head(20)

0          Paracetamol
1             Dolo 650
2               Crocin
3            Metformin
4         Azithromycin
5          Amoxicillin
6         Pantoprazole
7             Cefixime
8         Atorvastatin
9          Montelukast
10          Cetirizine
11           Augmentin
12      Cetirizine 792
13        Dolo 650 661
14     Paracetamol 477
15       Augmentin 265
16    Azithromycin 865
17       Metformin 836
18       Metformin 715
19          Crocin 386
Name: medicine_name, dtype: object

In [43]:
products["medicine_name"].nunique()

2261

In [44]:
products["medicine_name"].duplicated().sum()

np.int64(239)

In [45]:
products[
products["medicine_name"]
.duplicated(keep=False)
].head(20)

,product_id,medicine_name,category,manufacturer,cost_price,selling_price,expiry_days
41,MED000042,Atorvastatin 719,Neurology,Sun Pharma,1966.94,2678.98,646
49,MED000050,Augmentin 581,Antibiotics,Sun Pharma,3468.69,7127.67,274
79,MED000080,Dolo 650 242,Antibiotics,Sun Pharma,393.56,805.24,611
86,MED000087,Dolo 650 769,Diabetes,Mankind,1534.59,1744.30,289
91,MED000092,Amoxicillin 608,Analgesics,Dr Reddy's,1332.87,1546.36,788
92,MED000093,Crocin 990,Respiratory,Dr Reddy's,1501.71,2890.73,353
94,MED000095,Amoxicillin 330,Gastro,Dr Reddy's,536.71,689.75,336
97,MED000098,Azithromycin 793,Cardiology,Cipla,3170.52,3917.13,256
100,MED000101,Cetirizine 565,Dermatology,Glenmark,1001.39,2104.29,482
105,MED000106,Augmentin 834,Analgesics,Mankind,2413.94,5716.95,956
110,MED000111,Azithromycin 941,Cardiology,Dr Reddy's,964.89,1725.79,794
111,MED000112,Cetirizine 780,Antibiotics,Zydus,1754.59,2278.72,537
115,MED000116,Cetirizine 402,Antibiotics,Glenmark,1657.48,2203.27,525
121,MED000122,Pantoprazole 206,Analgesics,Mankind,1262.95,2132.52,1037
122,MED000123,Azithromycin 970,Cardiology,Dr Reddy's,1519.70,1781.01,1032
124,MED000125,Metformin 853,Cardiology,Torrent,1941.36,3095.99,1027
129,MED000130,Cetirizine 404,Antibiotics,Sun Pharma,2466.32,5166.69,734
133,MED000134,Cefixime 166,Dermatology,Torrent,3066.28,6077.55,426
144,MED000145,Pantoprazole 931,Neurology,Cipla,3417.09,7171.94,222
149,MED000150,Crocin 174,Diabetes,Zydus,475.39,656.22,1086

In [46]:
products.describe()

        cost_price  selling_price  expiry_days
count  2500.000000    2500.000000    2500.0000
mean   1771.998448    3066.947952     628.2048
std    1003.468224    1914.321396     266.1348
min      13.330000      17.430000     180.0000
25%     915.312500    1508.102500     390.0000
50%    1789.165000    2945.270000     621.5000
75%    2610.907500    4414.655000     857.0000
max    3499.920000    8266.460000    1095.0000

In [47]:
(products["selling_price"] <
 products["cost_price"]).sum()

np.int64(0)

In [48]:
(products["expiry_days"] <= 0).sum()

np.int64(0)

In [49]:
(
(products["selling_price"]-
products["cost_price"])
/
products["cost_price"]
*100
).describe()

count    2500.000000
mean       73.213712
std        39.023244
min         5.001770
25%        38.681345
50%        74.466625
75%       106.293188
max       139.927963
dtype: float64

In [50]:
(products["selling_price"] <
 products["cost_price"]).sum()

np.int64(0)

In [51]:
(products["expiry_days"] <= 0).sum()

np.int64(0)

In [52]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     2500 non-null   object
 1   medicine_name  2500 non-null   object
 2   category       2500 non-null   object
 3   manufacturer   2500 non-null   object
 4   cost_price     2500 non-null   float64
 5   selling_price  2500 non-null   float64
 6   expiry_days    2500 non-null   int64
dtypes: float64(2), int64(1), object(4)
memory usage: 136.8+ KB

In [53]:
products.to_csv(
"../Data/Cleaned/products_clean.csv",
index=False
)

print("products.csv cleaning completed")

products.csv cleaning completed

In [54]:
inventory.shape

(40500, 7)

In [55]:
inventory.isnull().sum()

inventory_id        0
product_id          0
city                0
stock_in            0
stock_out           0
current_stock       0
inventory_status    0
dtype: int64

In [56]:
inventory.duplicated().sum()

np.int64(500)

In [57]:
inventory.drop_duplicates(
inplace=True
)

In [58]:
inventory.duplicated().sum()

np.int64(0)

In [59]:
inventory.shape

(40000, 7)

In [60]:
inventory.dtypes

inventory_id        object
product_id          object
city                object
stock_in             int64
stock_out            int64
current_stock        int64
inventory_status    object
dtype: object

In [61]:
inventory["city"].value_counts()

city
Mumbai       8162
Hyderabad    8020
Pune         8015
Ahmedabad    7946
Delhi        7857
Name: count, dtype: int64

In [62]:
inventory["inventory_status"].value_counts()

inventory_status
Healthy      18777
Stockout     11943
Overstock     5980
Low Stock     3300
Name: count, dtype: int64

In [63]:
(
(
inventory["stock_in"]
-
inventory["stock_out"]
)
!=
inventory["current_stock"]
).sum()

np.int64(0)

In [64]:
(
inventory["current_stock"] < 0
).sum()

np.int64(11928)

In [65]:
inventory.loc[
inventory["current_stock"] < 0,
"inventory_status"
] = "Stockout"

In [66]:
inventory.loc[
inventory["current_stock"] < 0,
"current_stock"
] = 0

In [67]:
(
inventory["current_stock"] < 0
).sum()

np.int64(0)

In [68]:
inventory["inventory_status"].value_counts()

inventory_status
Healthy      18777
Stockout     11943
Overstock     5980
Low Stock     3300
Name: count, dtype: int64

In [69]:
inventory.to_csv(
"../Data/Cleaned/inventory_clean.csv",
index=False
)

print("inventory_clean.csv saved")

inventory_clean.csv saved

In [71]:
suppliers.shape

(800, 5)

In [72]:
suppliers.isnull().sum()

supplier_id        0
supplier_name      0
delivery_days      0
city               0
supplier_rating    0
dtype: int64

In [73]:
suppliers.duplicated().sum()

np.int64(0)

In [74]:
suppliers.dtypes

supplier_id         object
supplier_name       object
delivery_days        int64
city                object
supplier_rating    float64
dtype: object

In [75]:
suppliers["city"].value_counts()

city
Mumbai       243
Delhi        188
Hyderabad    166
Pune         115
Ahmedabad     88
Name: count, dtype: int64

In [76]:
suppliers["delivery_days"].describe()

count    800.000000
mean       8.786250
std        4.886247
min        1.000000
25%        5.000000
50%        8.000000
75%       12.000000
max       26.000000
Name: delivery_days, dtype: float64

In [77]:
suppliers["supplier_rating"].describe()

count    800.000000
mean       3.805375
std        0.751708
min        1.000000
25%        3.300000
50%        3.800000
75%        4.300000
max        5.000000
Name: supplier_rating, dtype: float64

In [78]:
suppliers.to_csv(
"../Data/Cleaned/suppliers_clean.csv",
index=False
)

print("suppliers_clean.csv saved")

suppliers_clean.csv saved

In [80]:
import pandas as pd

sales_transactions = pd.read_csv(
"../Data/Raw/sales_transactions.csv"
)

In [81]:
sales_transactions.shape

(193000, 15)

In [82]:
sales_transactions.isnull().sum()

order_id               0
order_date             0
customer_id            0
product_id             0
supplier_id         5250
city                4064
channel                0
quantity               0
unit_price             0
discount_pct           0
revenue                0
profit                 0
returned               0
return_reason     180803
payment_method         0
dtype: int64

In [83]:
sales_transactions["supplier_id"]=(
sales_transactions["supplier_id"]
.fillna("Unknown")
)

In [84]:
sales_transactions["city"]=(
sales_transactions["city"]
.fillna("Unknown")
)

In [85]:
sales_transactions[
"returned"
].value_counts()

returned
No     180518
Yes      4197
YES      4173
Y        4112
Name: count, dtype: int64

In [86]:
sales_transactions["returned"]=(
sales_transactions["returned"]
.replace({
"YES":"Yes",
"Y":"Yes"
})
)

In [87]:
sales_transactions[
"returned"
].value_counts()

returned
No     180518
Yes     12482
Name: count, dtype: int64

In [88]:
sales_transactions.isnull().sum()

order_id               0
order_date             0
customer_id            0
product_id             0
supplier_id            0
city                   0
channel                0
quantity               0
unit_price             0
discount_pct           0
revenue                0
profit                 0
returned               0
return_reason     180803
payment_method         0
dtype: int64

In [89]:
sales_transactions.loc[
sales_transactions["returned"]=="No",
"return_reason"
] = "Not Returned"

In [90]:
sales_transactions["return_reason"] = (
sales_transactions["return_reason"]
.fillna("Unknown")
)

In [91]:
sales_transactions.isnull().sum()

order_id          0
order_date        0
customer_id       0
product_id        0
supplier_id       0
city              0
channel           0
quantity          0
unit_price        0
discount_pct      0
revenue           0
profit            0
returned          0
return_reason     0
payment_method    0
dtype: int64

In [92]:
sales_transactions.duplicated().sum()

np.int64(3000)

In [93]:
sales_transactions = (
sales_transactions
.drop_duplicates()
)

In [94]:
sales_transactions.shape

(190000, 15)

In [95]:
sales_transactions.dtypes

order_id           object
order_date         object
customer_id        object
product_id         object
supplier_id        object
city               object
channel            object
quantity            int64
unit_price        float64
discount_pct      float64
revenue           float64
profit            float64
returned           object
return_reason      object
payment_method     object
dtype: object

In [98]:
sales_transactions["order_date"] = pd.to_datetime(
sales_transactions["order_date"],
format="mixed",
errors="coerce"
)

In [99]:
sales_transactions["order_date"].isnull().sum()

np.int64(126551)

In [100]:
sales_transactions["order_date"].head(20)

0    2023-04-15
1           NaT
2           NaT
3           NaT
4    2024-03-17
5    2022-01-25
6           NaT
7           NaT
8           NaT
9           NaT
10          NaT
11          NaT
12   2021-07-09
13   2023-10-25
14          NaT
15          NaT
16          NaT
17   2025-07-21
18          NaT
19          NaT
Name: order_date, dtype: datetime64[ns]

In [101]:
sales_transactions = pd.read_csv(
"../Data/Raw/sales_transactions.csv"
)

In [102]:
sales_transactions["order_date"].head()

0     2023-04-15
1    Jan 14 2024
2     20/10/2024
3    Jan 04 2020
4     2024-03-17
Name: order_date, dtype: object

In [103]:
sales_transactions["order_date"] = pd.to_datetime(
    sales_transactions["order_date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

In [104]:
sales_transactions["order_date"].isnull().sum()

np.int64(0)

In [106]:
sales_transactions = (
sales_transactions
.drop_duplicates()
)

In [107]:
sales_transactions["order_date"].describe()

count                           190000
mean     2023-01-09 13:14:45.524210176
min                2020-01-01 00:00:00
25%                2021-07-23 00:00:00
50%                2023-01-03 00:00:00
75%                2024-07-24 00:00:00
max                2025-12-27 00:00:00
Name: order_date, dtype: object

In [108]:
sales_transactions["quantity"].describe()

count    190000.000000
mean         32.195132
std          40.706670
min        -400.000000
25%          10.000000
50%          20.000000
75%          39.000000
max         400.000000
Name: quantity, dtype: float64

In [109]:
sales_transactions["quantity"] = (
sales_transactions["quantity"]
.abs()
)

In [110]:
sales_transactions["quantity"].describe()

count    190000.000000
mean         32.493037
std          40.469271
min           1.000000
25%          10.000000
50%          20.000000
75%          39.000000
max         400.000000
Name: quantity, dtype: float64

In [111]:
(
sales_transactions["quantity"]==0
).sum()

np.int64(0)

In [112]:
sales_transactions["discount_pct"].describe()

count    190000.000000
mean         12.813746
std          11.167302
min           0.000000
25%           6.600000
50%          12.040000
75%          17.500000
max         149.970000
Name: discount_pct, dtype: float64

In [113]:
sales_transactions.loc[
sales_transactions["discount_pct"] > 100,
"discount_pct"
] = 100

In [114]:
sales_transactions["discount_pct"].describe()

count    190000.000000
mean         12.680336
std           9.847135
min           0.000000
25%           6.600000
50%          12.040000
75%          17.500000
max         100.000000
Name: discount_pct, dtype: float64

In [115]:
sales_transactions["revenue"].describe()

count    1.900000e+05
mean     8.908390e+04
std      1.467867e+05
min      2.722000e+01
25%      1.509542e+04
50%      4.156151e+04
75%      1.019154e+05
max      3.105644e+06
Name: revenue, dtype: float64

In [116]:
sales_transactions["profit"].describe()

count    1.900000e+05
mean     2.868897e+04
std      6.380196e+04
min     -1.493610e+06
25%      2.048565e+03
50%      9.987760e+03
75%      3.203989e+04
max      1.771785e+06
Name: profit, dtype: float64

In [117]:
(
sales_transactions["profit"] < 0
).mean()*100

np.float64(10.228421052631578)

In [118]:
sales_transactions["profit"] = (
sales_transactions["profit"]
.clip(
lower=
sales_transactions["profit"]
.quantile(0.05)
)
)

In [119]:
(
sales_transactions["profit"] < 0
).mean()*100

np.float64(10.228421052631578)

In [ ]:
sales_transactions.to_csv(
"../Data/Cleaned/sales_transactions_clean.csv",
index=False
)

print("sales_transactions_clean.csv saved")

sales_transactions_clean.csv saved

: